version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_NAME=CMS
      - APP_ENV=docker
      - APP_KEY=base64:your_app_key_here
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
      - adminer
    networks:
      - laravel
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "4306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  dbdata: